### ISSUE TITLE
detail namespace should not be usable

### ISSUE THREAD

**Issue by ltabis** [Armillus/Delegate#1]
code under `namespace detail` should not be used by the user of the library (l.60).

You can actually type `namespace` instead of `namespace details`, it achieves the same result as static functions in C, keeping your implementation inside the file.

**Comment by Armillus** [comment]
Hello @ltabis,

Thank you for your issue!

It is true that anonymous namespaces can hide the code by making every symbol declared into them internal, like static functions.

However, you've probably noticed that functions into this namespace aren't static neither. This is due to the fact that using either of these constructs (anonymous namespaces or static functions) in header files is definitely discouraged by several C++ coding styles.

I'll let you search for more details if you want, but by using internal linkage in a header file, all the internal (or private) symbols will be redeclared for each translation unit (.cpp file), which is probably not the expected behaviour.

Although it could be useful for header-only libraries like this one, I prefer to stick to most C++ coding styles. Moreover, this library is still in development and some name clashes could arise by using an anonymous namespace. 

I hope you've understood my point of view (hopefully I convinced you), let me know if I can help you in any way :)

**Comment by ltabis** [comment]
If you do this because you want to stick to a particular C++ coding style, it alright for me !

> I'll let you search for more details if you want, but by using internal linkage in a header file, all the internal (or private) symbols will be redeclared for each translation unit (.cpp file) including this header, which is probably not the expected behaviour.

I need to look into this, it looks terrible :confused:

Closing this :smile:
